"""Coluna quantity not null

Revision ID: 1ed64b239569
Revises: 271a7afe135b
Create Date: 2022-09-04 16:15:44.528286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ed64b239569'
down_revision = '271a7afe135b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('purchase_order', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('purchase_order', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
