"""Adicionando coluna quantidade na tabela purchase_orders

Revision ID: 271a7afe135b
Revises: 
Create Date: 2022-09-04 16:12:18.951141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '271a7afe135b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_order', sa.Column('quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_order', 'quantity')
    # ### end Alembic commands ###
